### PR TITLE
Resolved discrepancy between page rendered w/ hugo and when rendered …

### PR DESCRIPTION
**Pull request by GerardWalsh**
…locally with RStudio

### CODE REVIEW

**Comment by datawookie** [comment]
So it was a whitespace issue?

@gerrywalsh I've just merged this. Give it a moment to build and then please go and check.

**Comment by GerardWalsh** [comment]
I think so, as well as some inconsistent spacing.

**Comment by datawookie** [comment]
Is it working now?

**Comment by GerardWalsh** [comment]
over here
https://exegetic-test.netlify.com/internal/procedure-version-control/ , it
looks just fine to me?

**Comment by datawookie** [comment]
That's all I wanted to know. Well played.

**Comment by datawookie** [comment]
Deleted your branch.

**Pull request merged**
