### PR TITLE
Merge request: coding-policy document

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by datawookie** [comment]
Thanks. I've created an issue with feedback. I've also sent you a
collaborator invite. Please accept so that I can assign the issue to you.

**Comment by datawookie** [comment]
@marinuslouw what's the status with this? I'd like to wrap it up by tomorrow. Please get feedback from @gerrywalsh too.

**Comment by ghost** [comment]
I am finished with all the edits. Just have to still critique Gerard's and have him critique mine, which we arranged will be done first thing tomorrow.

**Comment by datawookie** [comment]
Magic! Looking forward to getting these documents nailed down. Going to be rather nice to have some standards. :)

**Comment by datawookie** [comment]
Okay, we're not done with this, but I'm merging the branch so that you can see the results. Please see here for staging deploy of site: https://exegetic-test.netlify.com/internal/.

**Pull request merged**
