### PR TITLE
Version control

### PR DESCRIPTION
**Pull request by GerardWalsh**

### CODE REVIEW

**Comment by datawookie** [comment]
Thanks for the changes.

- Commit Messages. I think that the single line about commit messages is adequate for the policy. Should then have a section on commit messages in the procedure. Remember the distinction between these two documents is What (policy) and How (procedure).
- Connecting to Remote Repository. You have not covered how to connect an existing (local) repository to a remote repository.
- Merge Requests. You have some R-specific instructions. It would make sense to create a new sub-section for those.

**General**

- Please check spelling and grammar.
- Please use Title Case for all headings.

Thanks!

**Comment by datawookie** [comment]
@gerrywalsh  what's the status with this? I'd like to wrap it up by tomorrow. Please get feedback from @marinuslouw too.

**Comment by GerardWalsh** [comment]
Regarding commit messages and a separate section? This will be hard to fit
in as it is in reference to pushing changes a remote repo - maybe a
sub-heading?

**Comment by datawookie** [comment]
Why can't we just have a H2 level heading for "Commit Messages"? I think that this is as important (if not more so) than "Branches", for instance. No reason why it should not have it's own section.

**Comment by GerardWalsh** [comment]
Sure thing

**Comment by datawookie** [comment]
Okay, we're not done with this, but I'm merging the branch so that you can see the results. Please see here for staging deploy of site: https://exegetic-test.netlify.com/internal/.

**Pull request merged**
